config:
  target: "http://localhost:8080"
  phases:
    - duration: 20   # duración en segundos
      arrivalRate: 10 # usuarios virtuales por segundo
  #defaults:
    #headers:
      #Content-Type: "application/json"

scenarios:
  - name: "Usuarios (Test + Registración + Login)"
    flow:
      - log: "Crear Datos Fake de Usuario"
      - get:
          url: "/api/users/test"
          capture:
            - json: "$.name"
              as: "name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: "Registrar Usuario"
      - post:
          url: "/api/users/create"
          json:
            name: "{{name}}"
            email: "{{email}}"
            password: "{{password}}"
      - log: "Login Usuario"
      - post:
          url: "/api/users/login"
          json:
            email: "{{email}}"
            password: "{{password}}"    